### ISSUE TITLE
[Feature Request] 2 New Behaviors 

### ISSUE THREAD

**Issue by FelipeRearden** [nmady/obsidian-multi-line-formatting#2]
Hello again @nmady !!!!

I recently changed my workflow and I would like to make a feature request to see if you could help me :)

My Feature Request is a 2 new behavior for Multi-line Formatting when there is no `text selected`

## Multi-Line Today

**Behavior A**: When I press the command for Multi-line where there is no text select —> nothing happens

**Behavior B**: When I press the command for Multi-line where the text cursor (caret) is placed inside a word —> nothing happens

## My Feature Request

Would be amazing to have a way to implement `Behavior A` And `Behavior B` Inside the plug-in  :)

 ---

Thanks for reading this! Let me know if you need more information!

I wish you a fantastic day

**Comment by nmady** [comment]
Hi @FelipeRearden 

Thanks for reporting this, as I think there is a bug involved. 

The intended behaviour is for the formatting to be applied around your cursor. I'm releasing a new version to repair the behaviour. If you could please update your installation of the plugin and see if the changes offer your desired behaviour, and let me know! If the change isn't what you were looking for, from your description, I think I understand the aspects of what the plugin is doing now that you are interested in seeing changed, but not what you would like to see happen when you apply formatting. If you could provide more explanation, that would be great!

Thanks again for the feedback.

**Comment by FelipeRearden** [comment]
Hello @nmady !!!

Thank for your fast answer! 

I saw your message and I already update for the new version `0.3.3`. Here is my feedback:

> The intended behaviour is for the formatting to be applied around your cursor. I'm releasing a new version to repair the behaviour.

This is my  `Behaviour A` and works perfect :) :) :) —> thank you so much !!!!

>  I think I understand the aspects of what the plugin is doing now that you are interested in seeing changed, but not what you would like to see happen when you apply formatting. If you could provide more explanation, that would be great!

 I will try to explain what I am looking for in `Behaviour B`:

Example:
- I have the word `Hello beautiful world` in line 3:
- I’m gonna use the character `|` to represent the caret mouse cursor 
- I have a Multi-Line command -> Left: `<u>` and Right: `</u>`

The text cursor is placed “inside” the word beautiful like this:
- Hello be`|`autiful world  
![0FA3F9FB-13B3-4041-9563-7DDE3CECD078](https://user-images.githubusercontent.com/85180696/133907065-af470603-12b2-43de-b860-2368de645330.jpeg)


When I press my Multi-line here is what I’am expecting:
- Hello `<u>`beautiful`</u>`|  world 
![06AF45BC-2C4A-4D8D-92EC-04E265FC3D52](https://user-images.githubusercontent.com/85180696/133907069-73e6b6e5-b994-4b79-a906-6a1e1587d2a1.jpeg)
 

Here is what version `0.3.3` Is doing:
- Hello be`<u>`|`</u>`autiful world
![2835ECC9-9417-4106-B9C2-947819EF687D](https://user-images.githubusercontent.com/85180696/133907096-c38ae364-8036-4376-a8fd-4adde37787e2.jpeg)

---

Let me know if you need more information (maybe what I want is not even possible to do in Obsidian)

It’s a pleasure talking to you again :) Thanks for your help

**Comment by nmady** [comment]
Hi @FelipeRearden !

If you update to 0.4.0 and, in your settings, toggle **Format word if selection is empty** on for each of your formatting styles, I've implemented something close to Behaviour B. I believe the only difference from what you demonstrated in your screenshots is that I'm leaving the cursor where it was rather than jumping to the end of the word. Leaving the cursor where it was felt more intuitive to me, but I could probably be convinced to change that. :)

I hope you start using this new feature and let me know whether it is working the way you hoped! (And also let me know if I broke anything else in the process :stuck_out_tongue:)

**Comment by FelipeRearden** [comment]
Hello @nmady !!!!!!!!!!!!!!!!!!!!!

> I hope you start using this new feature and let me know whether it is working the way you hoped! 

Thank you so much for this new version. Behavior B is working perfect !!!!!!!!
- I loved the new toggle, it’s a great ideia to let user decide this by style :)

### Here is my feedback: 
> I've implemented something close to Behaviour B. I believe the only difference from what you demonstrated in your screenshots is that I'm leaving the cursor where it was rather than jumping to the end of the word. Leaving the cursor where it was felt more intuitive to me, but I could probably be convinced to change that. :)

I agree with you. Makes more sense leaving the cursor where it is :)

> (And also let me know if I broke anything else in the process 😛)

Unfortunately, I found a new little bug ONLY when **toggle `Format word if selection is empty` is ON.** Take a look:

I have a note with 3 lines. 
![D3BEB141-2FA6-4166-B78A-00F853F45EB3](https://user-images.githubusercontent.com/85180696/133935751-552766f5-4b86-4748-9a93-36ad76574457.jpeg)


Look what happens when my cursor is in the last line (line 3) and I press the Multi-Line command:
![EB8BF85E-E408-4D92-86BB-172E65FF9411](https://user-images.githubusercontent.com/85180696/133935725-428f886d-7861-4a1a-abaf-f922bb44b619.jpeg)

Now I’m gonna do the same command on line 2
![1BB04A0C-1704-49A6-A80F-8404A146084A](https://user-images.githubusercontent.com/85180696/133935774-a5158198-223a-423d-8bda-6d6d1e3785b2.jpeg)

Looks like that when I have an empty line after the line that the cursor is placed, we have this
![AC4E1517-B432-433E-A87C-94B3FD98929D](https://user-images.githubusercontent.com/85180696/133936042-79366341-aa33-403f-8d64-b9bd5179b9d9.jpeg)


BUT, When the next line is not empty. Everything is perfect
![0E54E090-ED9E-41DE-BD02-EBBBFC919E41](https://user-images.githubusercontent.com/85180696/133935845-8d27c018-40aa-491d-8eda-29f6fb6781cd.jpeg)

![7BBBC759-9F82-4B06-B8DD-4E4248C931B0](https://user-images.githubusercontent.com/85180696/133935850-d68f27a6-1979-4679-9276-0ed9323aef05.jpeg)

--- 

I’m sorry to bring you more problems :( but we are getting pretty close to make this perfect :)

Thanks for helping with this new feature :)

**Comment by nmady** [comment]
Hi @FelipeRearden !

I'm glad it is working close to the way you'd like! I am, however, having trouble reproducing that bug, which I did not expect and makes it harder to repair. I'm wondering if it might be due to interaction with another plugin. 

What operating system are you using Obsidian on?
Does the bug happen consistently? Does it happen with all of your formatting styles? Would you try turning off your other plugins to see if it still happens?
If those questions don't help us figure it out, it might be worth attaching your `.obsidian/plugins/multi-line-formatting/data.json` settings file to see if there is something specific going on in there.

Thanks for your help!
Nadia

**Comment by FelipeRearden** [comment]
Hello @nmady !!!!!!!!

Sorry for the late reply! Yesterday was a hard day for me :)

I'm sorry that was not possible to reproduce on your end. I hope I can help with the tests that I will describe below:

> What operating system are you using Obsidian on?  

I have two different vaults on Windows 10 and MacOS 11

The same "problem" exist in both OS

Just wanna emphasize that it only happens when **`Format word if selection is empty` is ON**
![Screen Shot 2021-09-24 at 07 43 18](https://user-images.githubusercontent.com/85180696/134664001-e9144be2-48b5-4959-9e64-a0cea203f4d8.png)

> Does the bug happen consistently? Does it happen with all of your formatting styles? Would you try turning off your other plugins to see if it still happens?

Before write this message I created a new vault and start from zero only installing Multi-line plugin:
- Did the same text with default style: Cyan Highlighter
- I created a new style 
- I changed the text 
- Reload Obsidian and reload the Plug-in

The same behaviour as before :(

> If those questions don't help us figure it out, it might be worth attaching your .obsidian/plugins/multi-line-formatting/data.json settings file to see if there is something specific going on in there.

Git doesn't support .json. I saved as a .txt file 
[datajson.txt](https://github.com/nmady/obsidian-multi-line-formatting/files/7225151/datajson.txt)

![Screen Shot 2021-09-24 at 08 04 26](https://user-images.githubusercontent.com/85180696/134664624-4db2e578-bec9-43db-b200-c688f06cdab2.png)

I'm doing my tests in this style: 
![Screen Shot 2021-09-24 at 07 54 29](https://user-images.githubusercontent.com/85180696/134664715-afb74b15-5f3e-46fd-b0f0-3c10e6023c35.png)

---

I hope it is an easy one 🙏 let me know if I can help with something.

Thanks again for all your help :)

**Comment by nmady** [comment]
Hi @FelipeRearden !

Thanks so much for all of your help so far. I got the bug to show itself a couple of times, but I didn't really locate the cause. Weirdly, the bug occurred when I used the command palette to call the command, but not when using hotkeys. I didn't expect those to have different behaviour!

However, this experiment did cause me to locate and fix _a_ bug (I had a mistake in my use of the Obsidian API), and now what I was doing to produce the bug doesn't work, which might mean I fixed the problem of interest. Give 0.4.1 a go and let me know if you can still make the bug show up! 

Thanks again :)

**Comment by FelipeRearden** [comment]
Hello @nmady !!!!

It’s funny because we learn something new with everybody that we talk. I never could imagine a diference between command palette and hotkeys.
- My real workflow is with hotkeys (of course) and I’m doing the tests with command palette instead. 
- You are right, 100% perfect with hotkeys in every test possible :) 

I have to be honest with you: the bug still show up in `0.4.1` **Only with Command Palette** :(
- My intuition says that its press return 2 times in command palette between `right` and `left` —> right+enter+left 

BUT, my workflow is 100% with hotkeys. So I’m 3000% happy with the way that things are in `0.4.1`. I think we can close for now and wait for someone else opinion. 
- I’m gonna start to migrate to my main vault !!!!!!!!!

As always you can count on me to test anything if/when you decide to track this issue again. I’m always here :)

- - - 

Thanks again for helping me and your patience with my feedback.
     
I wish you a fantastic day :)

**Comment by nmady** [comment]
Hey @FelipeRearden :)

This is a really sneaky bug. With the updates I made to 0.4.1, I can't seem to get the bug to happen, even with the command palette. 

> My intuition says that its press return 2 times in command palette between right and left —> right+enter+left

Can you explain that in a different way? I don't think I understand.

Since it mostly works, I think you're right that we can leave it this way and I am pretty close to letting it be, but as one (probably) last check, can you open the Developer Console (ctrl+shift+i) and let me know if there are any weird errors when you use the command palette and get the bug?

**Comment by FelipeRearden** [comment]
@nmady !!!!

Great news: its working !!!!!! 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉  I can’t reproduce as well.

I was opening Obsidian to print the Developer Console to you and I remember that yesterday I started `0.4.1` from zero (uninstall + install) to start my migration without that test styles.
- I did the same test and it’s working 100% !!!!!!!!!

I will start my real workflow is the next days. If I saw something strange, I will print the Developer Console + send data.json to you. 
  
I’m sorry if I made some confusion, but I’m happy that is working.

---

> Can you explain that in a different way? I don't think I understand.

I have this style: Nickname: Underline 
Left >>> `<u>`
Right >>> `</u>`

My feeling was that when using Multi-line from command palette the style was doing this sequence of events
1- Left
2- Press enter (return) key
3- Right

Result ->
Line3: `<u>`
Line4: |`</u>`

---

If you agree, let me stress my usage in the next days  to see if I found something strange. 
- But I think the clean install was the secret that I should have done before my test on `0.4.1`


We talk soon. Thanks again for everything. You are an extremely kind person Nadia :)

**Comment by nmady** [comment]
That's fantastic news! 

Thank you so much for all your help. It has been such a pleasure working with you on getting this new feature up and running. You have been extremely kind too. :)

**Comment by FelipeRearden** [comment]
Thanks @nmady !!!! 

I'm very happy that we have this new features.  

I wish you a fantastic Monday.  We talk later :)

**Comment by FelipeRearden** [comment]
Hello @nmady !!!!!!

Everything is okay with the new features BUT I found this two errors in my Console that I think a should share with you: 

![Screen Shot 2021-10-06 at 11 14 01](https://user-images.githubusercontent.com/85180696/136222284-3b6f744b-35e4-4086-ac4a-9bd854adc818.png)

Only happens when I use the first two styles:
- looking in the console, I can see that the ID from these two commands are the default ones which are different from mine because I changed 
- Should I change the names for the default name?   

First Style
![Screen Shot 2021-10-06 at 11 11 02](https://user-images.githubusercontent.com/85180696/136223011-612e8491-cbae-4288-a8d6-ed21b8e12d67.png)

Second Style
![Screen Shot 2021-10-06 at 11 11 20](https://user-images.githubusercontent.com/85180696/136223082-ba89bd8e-0d22-4c3a-965a-79250b9c9636.png)

Here is my `data.json`
[datamultiline.txt](https://github.com/nmady/obsidian-multi-line-formatting/files/7294796/datamultiline.txt)


Let me know if I can help with something :)

Have a great day !!!!

**Comment by nmady** [comment]
Hi @FelipeRearden !

Thank you for reporting these errors. I am again struggling to replicate the problem. I tried using your `data.json`, with and without hotkeys, but it still didn't show up for me.

I don't think the ID for the plugin should cause this particular error; the ID should be pretty much arbitrary. My intention was for users to set up their own styles over top of the samples that are setup as default, so you've done exactly as I intended the plugin to be used. 

The error `Cannot read property 'type' of undefined` is more likely to be caused by something to do with the SectionCache—maybe it wasn't up to date when you applied the plugin. I knew that there was potential for some minor problems due to the Cache when I released the plugin.

Am I understanding correctly that the formatting still worked as expected?

**Comment by FelipeRearden** [comment]
Hello @nmady !!!

Thanks for your reply and sorry to keep bothering you!

> I am again struggling to replicate the problem. I tried using your data.json, with and without hotkeys, but it still didn't show up for me.

Sorry to hear that. Would be much easier if you could replicate it from your end :)

> I don't think the ID for the plugin should cause this particular error; the ID should be pretty much arbitrary. My intention was for users to set up their own styles over top of the samples that are setup as default, so you've done exactly as I intended the plugin to be used.

Good to know that my usage is not wrong :)

> I knew that there was potential for some minor problems due to the Cache when I released the plugin.

Just to see if I understood correctly: 
- I don't have to worry about this console error and I can keep using the plugin safety and forget about this error ? 

> Am I understanding correctly that the formatting still worked as expected?

Yes :) everything is working perfect !!!!!!!

Thanks again for your help. Have a great day!
